"""empty message

Revision ID: 79b8875f44ba
Revises: 
Create Date: 2022-04-05 23:00:01.003649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79b8875f44ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temps',
    sa.Column('userphone', sa.BigInteger(), nullable=False),
    sa.Column('smscode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('userphone')
    )
    op.create_index(op.f('ix_temps_smscode'), 'temps', ['smscode'], unique=True)
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('userphone', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('patronymic', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_users_userphone'), 'users', ['userphone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_userphone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_temps_smscode'), table_name='temps')
    op.drop_table('temps')
    # ### end Alembic commands ###
