"""empty message

Revision ID: ab425930743b
Revises: 79b8875f44ba
Create Date: 2022-04-05 23:00:24.476503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab425930743b'
down_revision = '79b8875f44ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('videotoken', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('vttime', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('strims', sa.ARRAY(sa.String(length=10)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strims')
    op.drop_column('users', 'vttime')
    op.drop_column('users', 'videotoken')
    # ### end Alembic commands ###
